### ISSUE TITLE
Running error via install remote gem

### ISSUE THREAD

**Issue by hahwul** [hahwul/XSpear#3]
```
xspear
/Users/hahwul/.rvm/gems/ruby-2.4.6/gems/bundler-2.0.2/lib/bundler/rubygems_integration.rb:63:in `rescue in validate': The gemspec at /Users/hahwul/HAHWUL/tool/XSpear/XSpear.gemspec is not valid. Please fix this gemspec. (Gem::InvalidSpecificationException)
The validation error was 'XSpear-1.0.0 contains itself (XSpear-1.0.0.gem), check your files list'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/gems/bundler-2.0.2/lib/bundler/rubygems_integration.rb:58:in `validate'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/gems/bundler-2.0.2/lib/bundler/source/path.rb:157:in `validate_spec'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/gems/bundler-2.0.2/lib/bundler/source/path.rb:171:in `block in load_spec_files'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/gems/bundler-2.0.2/lib/bundler/source/path.rb:165:in `each'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/gems/bundler-2.0.2/lib/bundler/source/path.rb:165:in `load_spec_files'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/gems/bundler-2.0.2/lib/bundler/source/path.rb:100:in `local_specs'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/gems/bundler-2.0.2/lib/bundler/source/path.rb:108:in `specs'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/gems/bundler-2.0.2/lib/bundler/definition.rb:758:in `block in converge_locked_specs'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/gems/bundler-2.0.2/lib/bundler/definition.rb:744:in `each'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/gems/bundler-2.0.2/lib/bundler/definition.rb:744:in `converge_locked_specs'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/gems/bundler-2.0.2/lib/bundler/definition.rb:247:in `resolve'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/gems/bundler-2.0.2/lib/bundler/definition.rb:170:in `specs'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/gems/bundler-2.0.2/lib/bundler/runtime.rb:108:in `block in definition_method'
	from /Users/hahwul/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:59:in `candidate?'
	from /Users/hahwul/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:92:in `setup'
	from /Users/hahwul/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:124:in `check'
	from /Users/hahwul/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
	from /Users/hahwul/.rvm/rubies/ruby-2.4.6/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	from /Users/hahwul/.rvm/rubies/ruby-2.4.6/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /Users/hahwul/.rvm/rubies/ruby-2.4.6/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /Users/hahwul/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	from /Users/hahwul/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50:in `block in run'
	from /Users/hahwul/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `each'
	from /Users/hahwul/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `run'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:10:in `<main>'
```

**Comment by hahwul** [comment]
아마도... rspec 정의 문제같음..

**Comment by hahwul** [comment]
개발 디렉토리에서 remote gem으로 실행해서 그럼(rvm 떄문에)
일반 디렉토리 기준으론 영향 없음
```
$ gem install XSpear 
Successfully installed XSpear-1.0.1
Parsing documentation for XSpear-1.0.1
Installing ri documentation for XSpear-1.0.1
Done installing documentation for XSpear after 0 seconds
1 gem installed
```

```
$ xspear -h
    )  (
 ( /(  )\ )
 )\())(()/(          (     )  (
((_)\  /(_))`  )    ))\ ( /(  )(
__((_)(_))  /(/(   /((_))(_))(()\
\ \/ // __|((_)_\ (_)) ((_)_  ((_)
 >  < \__ \| '_ \)/ -_)/ _` || '_|
/_/\_\|___/| .__/ \___|\__,_||_|    />
           |_|                   \ /<
{\\\\\\\\\\\\\BYHAHWUL\\\\\\\\\\\(0):::<======================-
                                 / \<
                                    \>
Usage: xspear -u [target] -[options] [value]
[ e.g ]
$ ruby a.rb -u 'https://www.hahwul.com/?q=123' --cookie='role=admin'

[ Options ]
    -u, --url=target_URL             [required] Target Url
    -d, --data=POST Body             [optional] POST Method Body data
        --headers=HEADERS            [optional] Add HTTP Headers
        --cookie=COOKIE              [optional] Add Cookie
    -p, --param=PARAM                [optional] Test paramters
    -t, --threads=NUMBER             [optional] thread , default: 10
    -o, --output=FILENAME            [optional] Save JSON Result
    -v, --verbose=1~3                [optional] Show log depth
                                      + Default value: 2
                                      + v=1 : quite mode
                                      + v=2 : show scanning log
                                      + v=3 : show detail log(req/res)
    -h, --help                       Prints this help
        --update                     Update with online
```
