### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by hahwul** [hahwul/XSpear#35]
```
xspear
/Users/hahwul/.rvm/rubies/ruby-2.4.6/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require': /Users/hahwul/.rvm/gems/ruby-2.4.6/gems/XSpear-1.2.2/lib/XSpear.rb:667: dynamic constant assignment (SyntaxError)
	from /Users/hahwul/.rvm/rubies/ruby-2.4.6/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/gems/XSpear-1.2.2/exe/XSpear:4:in `<top (required)>'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/bin/xspear:23:in `load'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/bin/xspear:23:in `<main>'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `eval'
	from /Users/hahwul/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by hahwul** [comment]
재현OS
```
- MacOS Catalina
- Ubuntu 18/04
```

디버깅 코드로 인한 Syntax error
```
      rescue => StandardError
```

to 

```
      rescue StandardError
```

**Comment by hahwul** [comment]
```
gem update XSpear
Updating installed gems
Updating XSpear
Fetching XSpear-1.2.3.gem
Successfully installed XSpear-1.2.3
Parsing documentation for XSpear-1.2.3
Installing ri documentation for XSpear-1.2.3
Installing darkfish documentation for XSpear-1.2.3
Done installing documentation for XSpear after 0 seconds
Parsing documentation for XSpear-1.2.3
Done installing documentation for XSpear after 0 seconds
Gems updated: XSpear
```

```
xspear -h
    )  (
 ( /(  )\ )
 )\())(()/(          (     )  (
((_)\  /(_))`  )    ))\ ( /(  )(
__((_)(_))  /(/(   /((_))(_))(()\
\ \/ // __|((_)_\ (_)) ((_)_  ((_)
 >  < \__ \| '_ \)/ -_)/ _` || '_|
/_/\_\|___/| .__/ \___|\__,_||_|    />
           |_|                   \ /<
{\\\\\\\\\\\\\BYHAHWUL\\\\\\\\\\\(0):::<======================-
                                 / \<
                                    \>       [ v1.2.3 ]
Usage: xspear -u [target] -[options] [value]
[ e.g ]
$ xspear -u 'https://www.hahwul.com/?q=123' --cookie='role=admin'

[ Options ]
    -u, --url=target_URL             [required] Target Url
    -d, --data=POST Body             [optional] POST Method Body data
    -a, --test-all-params            [optional] test to all params(include not reflected)
        --headers=HEADERS            [optional] Add HTTP Headers
        --cookie=COOKIE              [optional] Add Cookie
        --raw=FILENAME               [optional] Load raw file(e.g raw_sample.txt)
    -p, --param=PARAM                [optional] Test paramters
    -b, --BLIND=URL                  [optional] Add vector of Blind XSS
                                      + with XSS Hunter, ezXSS, HBXSS, etc...
                                      + e.g : -b https://hahwul.xss.ht
    -t, --threads=NUMBER             [optional] thread , default: 10
    -o, --output=FILENAME            [optional] Save JSON Result
    -v, --verbose=1~3                [optional] Show log depth
                                      + Default value: 2
                                      + v=1 : quite mode
                                      + v=2 : show scanning log
                                      + v=3 : show detail log(req/res)
    -h, --help                       Prints this help
        --version                    Show XSpear version
        --update                     Show how to update
```

Fixed
